name = "QMDDocTools"
uuid = "c50e25eb-ade4-4c96-a757-2a1fd62cbd8c"
authors = ["nhz2 <nhz2@cornell.edu> and contributors"]
version = "1.1.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
DataStructures = "0.18"
julia = "1.7"
