name = "QMDDocTools"
uuid = "c50e25eb-ade4-4c96-a757-2a1fd62cbd8c"
version = "1.2.0"
authors = ["nhz2 <nhz2@cornell.edu> and contributors"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
DataStructures = "0.18"
SHA = "0.7"
julia = "1.10"
